'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
	await queryInterface.bulkInsert('Entities', [
		{entity_code: 'AD', entity_name: 'Andorra'},
		{entity_code: 'AE', entity_name: 'United Arab Emirates'},
		{entity_code: 'AF', entity_name: 'Afghanistan'},
		{entity_code: 'AG', entity_name: 'Antigua and Barbuda'},
		{entity_code: 'AI', entity_name: 'Anguilla'},
		{entity_code: 'AL', entity_name: 'Albania'},
		{entity_code: 'AM', entity_name: 'Armenia'},
		{entity_code: 'AO', entity_name: 'Angola'},
		{entity_code: 'AQ', entity_name: 'Antarctica'},
		{entity_code: 'AR', entity_name: 'Argentina'},
		{entity_code: 'AS', entity_name: 'American Samoa'},
		{entity_code: 'AT', entity_name: 'Austria'},
		{entity_code: 'AU', entity_name: 'Australia'},
		{entity_code: 'AW', entity_name: 'Aruba'},
		{entity_code: 'AX', entity_name: 'Åland Islands'},
		{entity_code: 'AZ', entity_name: 'Azerbaijan'},
		{entity_code: 'BA', entity_name: 'Bosnia and Herzegovina'},
		{entity_code: 'BB', entity_name: 'Barbados'},
		{entity_code: 'BD', entity_name: 'Bangladesh'},
		{entity_code: 'BE', entity_name: 'Belgium'},
		{entity_code: 'BF', entity_name: 'Burkina Faso'},
		{entity_code: 'BG', entity_name: 'Bulgaria'},
		{entity_code: 'BH', entity_name: 'Bahrain'},
		{entity_code: 'BI', entity_name: 'Burundi'},
		{entity_code: 'BJ', entity_name: 'Benin'},
		{entity_code: 'BL', entity_name: 'Saint Barthélemy'},
		{entity_code: 'BM', entity_name: 'Bermuda'},
		{entity_code: 'BN', entity_name: 'Brunei Darussalam'},
		{entity_code: 'BO', entity_name: 'Bolivia (Plurinational State of)'},
		{entity_code: 'BQ', entity_name: 'Bonaire, Sint Eustatius and Saba'},
		{entity_code: 'BR', entity_name: 'Brazil'},
		{entity_code: 'BS', entity_name: 'Bahamas'},
		{entity_code: 'BT', entity_name: 'Bhutan'},
		{entity_code: 'BV', entity_name: 'Bouvet Island'},
		{entity_code: 'BW', entity_name: 'Botswana'},
		{entity_code: 'BY', entity_name: 'Belarus'},
		{entity_code: 'BZ', entity_name: 'Belize'},
		{entity_code: 'CA', entity_name: 'Canada'},
		{entity_code: 'CC', entity_name: 'Cocos (Keeling) Islands'},
		{entity_code: 'CD', entity_name: 'Congo, Democratic Republic of the'},
		{entity_code: 'CF', entity_name: 'Central African Republic'},
		{entity_code: 'CG', entity_name: 'Congo'},
		{entity_code: 'CH', entity_name: 'Switzerland'},
		{entity_code: 'CI', entity_name: 'Côte d\'Ivoire'},
		{entity_code: 'CK', entity_name: 'Cook Islands'},
		{entity_code: 'CL', entity_name: 'Chile'},
		{entity_code: 'CM', entity_name: 'Cameroon'},
		{entity_code: 'CN', entity_name: 'China'},
		{entity_code: 'CO', entity_name: 'Colombia'},
		{entity_code: 'CR', entity_name: 'Costa Rica'},
		{entity_code: 'CU', entity_name: 'Cuba'},
		{entity_code: 'CV', entity_name: 'Cabo Verde'},
		{entity_code: 'CW', entity_name: 'Curaçao'},
		{entity_code: 'CX', entity_name: 'Christmas Island'},
		{entity_code: 'CY', entity_name: 'Cyprus'},
		{entity_code: 'CZ', entity_name: 'Czechia'},
		{entity_code: 'DE', entity_name: 'Germany'},
		{entity_code: 'DJ', entity_name: 'Djibouti'},
		{entity_code: 'DK', entity_name: 'Denmark'},
		{entity_code: 'DM', entity_name: 'Dominica'},
		{entity_code: 'DO', entity_name: 'Dominican Republic'},
		{entity_code: 'DZ', entity_name: 'Algeria'},
		{entity_code: 'EC', entity_name: 'Ecuador'},
		{entity_code: 'EE', entity_name: 'Estonia'},
		{entity_code: 'EG', entity_name: 'Egypt'},
		{entity_code: 'EH', entity_name: 'Western Sahara'},
		{entity_code: 'ER', entity_name: 'Eritrea'},
		{entity_code: 'ES', entity_name: 'Spain'},
		{entity_code: 'ET', entity_name: 'Ethiopia'},
		{entity_code: 'FI', entity_name: 'Finland'},
		{entity_code: 'FJ', entity_name: 'Fiji'},
		{entity_code: 'FK', entity_name: 'Falkland Islands (Malvinas)'},
		{entity_code: 'FM', entity_name: 'Micronesia (Federated States of)'},
		{entity_code: 'FO', entity_name: 'Faroe Islands'},
		{entity_code: 'FR', entity_name: 'France'},
		{entity_code: 'GA', entity_name: 'Gabon'},
		{entity_code: 'GB', entity_name: 'United Kingdom of Great Britain and Northern Ireland'},
		{entity_code: 'GD', entity_name: 'Grenada'},
		{entity_code: 'GE', entity_name: 'Georgia'},
		{entity_code: 'GF', entity_name: 'French Guiana'},
		{entity_code: 'GG', entity_name: 'Guernsey'},
		{entity_code: 'GH', entity_name: 'Ghana'},
		{entity_code: 'GI', entity_name: 'Gibraltar'},
		{entity_code: 'GL', entity_name: 'Greenland'},
		{entity_code: 'GM', entity_name: 'Gambia'},
		{entity_code: 'GN', entity_name: 'Guinea'},
		{entity_code: 'GP', entity_name: 'Guadeloupe'},
		{entity_code: 'GQ', entity_name: 'Equatorial Guinea'},
		{entity_code: 'GR', entity_name: 'Greece'},
		{entity_code: 'GS', entity_name: 'South Georgia and the South Sandwich Islands'},
		{entity_code: 'GT', entity_name: 'Guatemala'},
		{entity_code: 'GU', entity_name: 'Guam'},
		{entity_code: 'GW', entity_name: 'Guinea-Bissau'},
		{entity_code: 'GY', entity_name: 'Guyana'},
		{entity_code: 'HK', entity_name: 'Hong Kong'},
		{entity_code: 'HM', entity_name: 'Heard Island and McDonald Islands'},
		{entity_code: 'HN', entity_name: 'Honduras'},
		{entity_code: 'HR', entity_name: 'Croatia'},
		{entity_code: 'HT', entity_name: 'Haiti'},
		{entity_code: 'HU', entity_name: 'Hungary'},
		{entity_code: 'ID', entity_name: 'Indonesia'},
		{entity_code: 'IE', entity_name: 'Ireland'},
		{entity_code: 'IL', entity_name: 'Israel'},
		{entity_code: 'IM', entity_name: 'Isle of Man'},
		{entity_code: 'IN', entity_name: 'India'},
		{entity_code: 'IO', entity_name: 'British Indian Ocean Territory'},
		{entity_code: 'IQ', entity_name: 'Iraq'},
		{entity_code: 'IR', entity_name: 'Iran (Islamic Republic of)'},
		{entity_code: 'IS', entity_name: 'Iceland'},
		{entity_code: 'IT', entity_name: 'Italy'},
		{entity_code: 'JE', entity_name: 'Jersey'},
		{entity_code: 'JM', entity_name: 'Jamaica'},
		{entity_code: 'JO', entity_name: 'Jordan'},
		{entity_code: 'JP', entity_name: 'Japan'},
		{entity_code: 'KE', entity_name: 'Kenya'},
		{entity_code: 'KG', entity_name: 'Kyrgyzstan'},
		{entity_code: 'KH', entity_name: 'Cambodia'},
		{entity_code: 'KI', entity_name: 'Kiribati'},
		{entity_code: 'KM', entity_name: 'Comoros'},
		{entity_code: 'KN', entity_name: 'Saint Kitts and Nevis'},
		{entity_code: 'KP', entity_name: 'Korea (Democratic People\'s Republic of)'},
		{entity_code: 'KR', entity_name: 'Korea, Republic of'},
		{entity_code: 'KW', entity_name: 'Kuwait'},
		{entity_code: 'KY', entity_name: 'Cayman Islands'},
		{entity_code: 'KZ', entity_name: 'Kazakhstan'},
		{entity_code: 'LA', entity_name: 'Lao People\'s Democratic Republic'},
		{entity_code: 'LB', entity_name: 'Lebanon'},
		{entity_code: 'LC', entity_name: 'Saint Lucia'},
		{entity_code: 'LI', entity_name: 'Liechtenstein'},
		{entity_code: 'LK', entity_name: 'Sri Lanka'},
		{entity_code: 'LR', entity_name: 'Liberia'},
		{entity_code: 'LS', entity_name: 'Lesotho'},
		{entity_code: 'LT', entity_name: 'Lithuania'},
		{entity_code: 'LU', entity_name: 'Luxembourg'},
		{entity_code: 'LV', entity_name: 'Latvia'},
		{entity_code: 'LY', entity_name: 'Libya'},
		{entity_code: 'MA', entity_name: 'Morocco'},
		{entity_code: 'MC', entity_name: 'Monaco'},
		{entity_code: 'MD', entity_name: 'Moldova, Republic of'},
		{entity_code: 'ME', entity_name: 'Montenegro'},
		{entity_code: 'MF', entity_name: 'Saint Martin (French part)'},
		{entity_code: 'MG', entity_name: 'Madagascar'},
		{entity_code: 'MH', entity_name: 'Marshall Islands'},
		{entity_code: 'MK', entity_name: 'North Macedonia'},
		{entity_code: 'ML', entity_name: 'Mali'},
		{entity_code: 'MM', entity_name: 'Myanmar'},
		{entity_code: 'MN', entity_name: 'Mongolia'},
		{entity_code: 'MO', entity_name: 'Macao'},
		{entity_code: 'MP', entity_name: 'Northern Mariana Islands'},
		{entity_code: 'MQ', entity_name: 'Martinique'},
		{entity_code: 'MR', entity_name: 'Mauritania'},
		{entity_code: 'MS', entity_name: 'Montserrat'},
		{entity_code: 'MT', entity_name: 'Malta'},
		{entity_code: 'MU', entity_name: 'Mauritius'},
		{entity_code: 'MV', entity_name: 'Maldives'},
		{entity_code: 'MW', entity_name: 'Malawi'},
		{entity_code: 'MX', entity_name: 'Mexico'},
		{entity_code: 'MY', entity_name: 'Malaysia'},
		{entity_code: 'MZ', entity_name: 'Mozambique'},
		{entity_code: 'NA', entity_name: 'Namibia'},
		{entity_code: 'NC', entity_name: 'New Caledonia'},
		{entity_code: 'NE', entity_name: 'Niger'},
		{entity_code: 'NF', entity_name: 'Norfolk Island'},
		{entity_code: 'NG', entity_name: 'Nigeria'},
		{entity_code: 'NI', entity_name: 'Nicaragua'},
		{entity_code: 'NL', entity_name: 'Netherlands, Kingdom of the'},
		{entity_code: 'NO', entity_name: 'Norway'},
		{entity_code: 'NP', entity_name: 'Nepal'},
		{entity_code: 'NR', entity_name: 'Nauru'},
		{entity_code: 'NU', entity_name: 'Niue'},
		{entity_code: 'NZ', entity_name: 'New Zealand'},
		{entity_code: 'OM', entity_name: 'Oman'},
	])
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
